#!/bin/bash
if [ $# -eq 0 ]; then
    echo "ERREUR"
    exit 1
fi
file=$1
n=0
while read -r line; do
    n=$((n + 1))
    status=$(curl -o /dev/null -s -w "%{http_code}\n" "$line")
    encoding=$(curl -s -I "$line" | grep -i "charset" | cut -d= -f2)
    nb_mots=$(curl -s "$line" | wc -w)
    echo -e "${n}\t${line}\tStatus: ${status}\tEncoding: ${encoding}\tWords: ${nb_mots}"
done < "$file"
